FROM openjdk:11-jre-slim
ENV LANG C.UTF-8

ENV JAVA_OPTS=-Duser.timezone=Asia/Seoul

RUN apt-get update && apt-get install -y bash && rm -rf /var/lib/apt/lists/*

COPY build/libs/wanted-pre-onboarding-backend-0.0.1-SNAPSHOT.jar /was/was.jar

COPY wait-for.sh /wait-for.sh
RUN chmod +x /wait-for.sh

ENTRYPOINT /bin/bash -c "/wait-for.sh db 3306 -- java $JAVA_OPTS -jar /was/was.jar"
