FROM openjdk:11-jre-slim
ENV LANG C.UTF-8

RUN apt-get update && apt-get install -y bash && rm -rf /var/lib/apt/lists/*

COPY build/libs/wanted-pre-onboarding-backend-0.0.1-SNAPSHOT.jar /was/was.jar

COPY wait-for.sh /wait-for.sh
RUN chmod +x /wait-for.sh

ENTRYPOINT ["/bin/bash", "/wait-for.sh", "db", "3306", "--", "java", "-jar", "/was/was.jar"]
