spring:
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/board?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: lvalentine
    password: lvalentine

  sql:
    init:
      schema-locations: classpath:init/01-schema.sql
      data-locations: classpath:init/02-data.sql
      mode: always

logging:
  level:
    root: info
